#pragma once
#include <GL/glew.h>
#include <GL/gl.h>
#include <GLFW/glfw3.h>
#include "debugging.h"
#include "Renderable.h"
#include "shaders.h"
#include "matrix_stack.h"
#include "simple_shapes.h"
#include <glm/ext.hpp>
#include <glm/gtx/string_cast.hpp>
